# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AgentGuard < Formula
  desc "AI Agent, CLI tools, and MCP server security scanning tool"
  homepage "https://github.com/imdlan/AIAgentGuard"
  version "1.4.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/imdlan/AIAgentGuard/releases/download/v1.4.0/agent-guard_1.4.0_darwin_amd64.tar.gz"
      sha256 "4b415c7b5fb9cd03c05b033dccb19dba368055dc9b97e6face77589ee0679e99"

      def install
        bin.install "agent-guard"
      end
    end
    on_arm do
      url "https://github.com/imdlan/AIAgentGuard/releases/download/v1.4.0/agent-guard_1.4.0_darwin_arm64.tar.gz"
      sha256 "4ace40499eef9836d5a9edc529b42a4d82902c7d962c6edc924628a1a2caaef0"

      def install
        bin.install "agent-guard"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/imdlan/AIAgentGuard/releases/download/v1.4.0/agent-guard_1.4.0_linux_amd64.tar.gz"
        sha256 "6bb689599bd195b46cd18d8543315055cc9dcfb750da9d9344c96bd9ebd00f17"

        def install
          bin.install "agent-guard"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/imdlan/AIAgentGuard/releases/download/v1.4.0/agent-guard_1.4.0_linux_arm64.tar.gz"
        sha256 "5425b1d2472e67e82f07298ccf721785f81bcd28c0b9306c34ebe66c5e0b6633"

        def install
          bin.install "agent-guard"
        end
      end
    end
  end

  test do
    system "#{bin}/agent-guard --help"
  end
end
