# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AgentGuard < Formula
  desc "AI Agent, CLI tools, and MCP server security scanning tool"
  homepage "https://github.com/imdlan/AIAgentGuard"
  version "1.4.1"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/imdlan/AIAgentGuard/releases/download/v1.4.1/agent-guard_1.4.1_darwin_amd64.tar.gz"
      sha256 "e2f79c96c62743585a83e53f182b3e5760002aa42ff002d9c2b7f1c09f7f43d6"

      def install
        bin.install "agent-guard"
      end
    end
    on_arm do
      url "https://github.com/imdlan/AIAgentGuard/releases/download/v1.4.1/agent-guard_1.4.1_darwin_arm64.tar.gz"
      sha256 "b0161db61e57f0702ae7e683bc91e7ced486c0096c9a5e370826635c2b703b72"

      def install
        bin.install "agent-guard"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/imdlan/AIAgentGuard/releases/download/v1.4.1/agent-guard_1.4.1_linux_amd64.tar.gz"
        sha256 "6e26a9ed047d4a5e7c658eb63dbe6a779e2c698306f2ccb17780d89f23f9fb8d"

        def install
          bin.install "agent-guard"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/imdlan/AIAgentGuard/releases/download/v1.4.1/agent-guard_1.4.1_linux_arm64.tar.gz"
        sha256 "f376038390652f686cbe74113554a64c1d274aa74c4792f4313ebcc1b62a3f89"

        def install
          bin.install "agent-guard"
        end
      end
    end
  end

  test do
    system "#{bin}/agent-guard --help"
  end
end
